import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

interface JsonSchemaNode {
  type?: string;
  properties?: Record<string, JsonSchemaNode>;
  required?: string[];
  items?: JsonSchemaNode;
  enum?: unknown[];
  description?: string;
}

interface AgentSummary {
  id: string;
  handle: string;
  name: string;
}

export interface GenerateOptions {
  agent?: string;
  all?: boolean;
  check?: boolean;
  outDir: string;
  apiUrl: string;
  token?: string;
}

function pascalCase(handle: string): string {
  return handle
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');
}

function camelCase(handle: string): string {
  const pascal = pascalCase(handle);
  return pascal[0].toLowerCase() + pascal.slice(1);
}

/** Render the JSON Schema subset agent schemas use as a TypeScript type. */
export function schemaToTsType(schema: JsonSchemaNode | null, indent = ''): string {
  if (!schema || schema.type === undefined) return 'Record<string, unknown>';

  if (schema.enum !== undefined) {
    return schema.enum.map((v) => JSON.stringify(v)).join(' | ');
  }

  switch (schema.type) {
    case 'string':
      return 'string';
    case 'number':
    case 'integer':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'null':
      return 'null';
    case 'array':
      return `Array<${schemaToTsType(schema.items ?? null, indent)}>`;
    case 'object': {
      const props = schema.properties ?? {};
      if (Object.keys(props).length === 0) return 'Record<string, unknown>';
      const required = new Set(schema.required ?? []);
      const inner = indent + '  ';
      const fields = Object.entries(props)
        .map(([key, prop]) => {
          const comment = prop.description ? `${inner}/** ${prop.description} */\n` : '';
          const optional = required.has(key) ? '' : '?';
          return `${comment}${inner}${JSON.stringify(key).replace(/"/g, '')}${optional}: ${schemaToTsType(prop, inner)};`;
        })
        .join('\n');
      return `{\n${fields}\n${indent}}`;
    }
    default:
      return 'unknown';
  }
}

export function renderTypesFile(
  handle: string,
  inputSchema: JsonSchemaNode | null,
  outputSchema: JsonSchemaNode | null,
): string {
  const base = pascalCase(handle);
  return `// Generated by \`magicaal generate\` — do not edit by hand.
// Agent: ${handle}

export type ${base}Input = ${schemaToTsType(inputSchema)};

export type ${base}Output = ${schemaToTsType(outputSchema)};
`;
}

export function renderDescriptorFile(
  agent: AgentSummary,
  inputSchema: JsonSchemaNode | null,
  outputSchema: JsonSchemaNode | null,
  schemaHash: string,
): string {
  const base = pascalCase(agent.handle);
  const constName = `${camelCase(agent.handle)}Agent`;
  return `// Generated by \`magicaal generate\` — do not edit by hand.
// Agent: ${agent.handle} (${agent.id})
import type { AgentDescriptor } from '@magicaal/sdk';
import type { ${base}Input, ${base}Output } from './${agent.handle}.types';

export const ${constName}: AgentDescriptor<${base}Input, ${base}Output> = {
  agentId: ${JSON.stringify(agent.id)},
  handle: ${JSON.stringify(agent.handle)},
  schemaHash: ${JSON.stringify(schemaHash)},
  inputSchema: ${JSON.stringify(inputSchema, null, 2)},
  outputSchema: ${JSON.stringify(outputSchema, null, 2)},
};
`;
}

export function computeSchemaHash(
  inputSchema: JsonSchemaNode | null,
  outputSchema: JsonSchemaNode | null,
): string {
  return createHash('sha256')
    .update(JSON.stringify({ inputSchema, outputSchema }))
    .digest('hex');
}

async function fetchJson<T>(url: string, token?: string): Promise<T | null> {
  const res = await fetch(url, {
    headers: token ? { Authorization: `Bearer ${token}` } : {},
  });
  if (res.status === 404) return null;
  if (!res.ok) {
    throw new Error(`${url} returned ${res.status}: ${await res.text()}`);
  }
  return (await res.json()) as T;
}

export async function generateCommand(opts: GenerateOptions): Promise<void> {
  const token = opts.token ?? process.env.MAGICAAL_API_TOKEN;
  if (!token) {
    console.error('An API token is required: pass --token or set MAGICAAL_API_TOKEN');
    process.exitCode = 1;
    return;
  }
  if (!opts.agent && !opts.all) {
    console.error('Specify --agent <handle> or --all');
    process.exitCode = 1;
    return;
  }

  const agents = await fetchJson<AgentSummary[]>(`${opts.apiUrl}/v1/agents`, token);
  if (!agents) {
    console.error('Failed to list agents');
    process.exitCode = 1;
    return;
  }

  const targets = opts.all
    ? agents
    : agents.filter((a) => a.handle === opts.agent || a.id === opts.agent);

  if (targets.length === 0) {
    console.error(`No agent found matching "${opts.agent}"`);
    process.exitCode = 1;
    return;
  }

  const outDir = resolve(process.cwd(), opts.outDir);
  if (!opts.check) mkdirSync(outDir, { recursive: true });

  let drifted = 0;

  for (const agent of targets) {
    const input = await fetchJson<{ inputSchema: JsonSchemaNode }>(
      `${opts.apiUrl}/v1/agents/${agent.id}/schema/input`,
      token,
    );
    const output = await fetchJson<{ outputSchema: JsonSchemaNode }>(
      `${opts.apiUrl}/v1/agents/${agent.id}/schema/output`,
      token,
    );

    const inputSchema = input?.inputSchema ?? null;
    const outputSchema = output?.outputSchema ?? null;
    const schemaHash = computeSchemaHash(inputSchema, outputSchema);

    const files: Array<{ path: string; content: string }> = [
      {
        path: join(outDir, `${agent.handle}.types.ts`),
        content: renderTypesFile(agent.handle, inputSchema, outputSchema),
      },
      {
        path: join(outDir, `${agent.handle}.descriptor.ts`),
        content: renderDescriptorFile(agent, inputSchema, outputSchema, schemaHash),
      },
    ];

    if (opts.check) {
      for (const file of files) {
        const existing = existsSync(file.path) ? readFileSync(file.path, 'utf8') : null;
        if (existing !== file.content) {
          console.error(`✗ drift: ${file.path}${existing === null ? ' (missing)' : ''}`);
          drifted++;
        }
      }
    } else {
      for (const file of files) {
        writeFileSync(file.path, file.content);
        console.log(`✓ wrote ${file.path}`);
      }
    }
  }

  if (opts.check) {
    if (drifted > 0) {
      console.error(`\n${drifted} file(s) out of date — run \`magicaal generate\` to refresh`);
      process.exitCode = 1;
    } else {
      console.log('✓ generated files are up to date');
    }
  }
}
